### ISSUE TITLE
how can we use push savings plan data as API directly into the Cost Management dashboard

### ISSUE THREAD

**Issue by sakshi-diwan** [sairashaik6677/azuresavingsdashboard#10]
hello Saira 

Can u help advise how can we push savings plan live data directly from Azure portal as an API to the cost Management dashboard.

also how can the savings plan can show exact same un-utilization as Azure Portal. there seems to be some discrepancy in the way the data is showing on Cost management dashboard vs what is showing in the Portal

**Comment by nataliiatho** [comment]
Hi Saira, I am  interested in the same question - direct connection to Azure portal as an API. As of now we are using Azure Cost Management connector - but I am not sure if its gonna work from 01.05.2024.
[Migrate from Azure Enterprise Reporting to Microsoft Cost Management APIs overview - Microsoft Cost Management | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cost-management-billing/automate/migrate-ea-reporting-arm-apis-overview)

**Comment by sairashaik6677** [comment]
I am not aware of any API to pull this data. 

Unused Savings plan calculations are fixed as per the latest public article - https://learn.microsoft.com/en-us/azure/cost-management-billing/reservations/calculate-ea-reservations-savings

**Comment by sairashaik6677** [comment]
Unused Savings plan calculations are fixed as per the latest public article - https://learn.microsoft.com/en-us/azure/cost-management-billing/reservations/calculate-ea-reservations-savings.

Take the latest .pbit file and setup guide.
