### ISSUE TITLE
Savings Plan and Reservations not being calculated

### ISSUE THREAD

**Issue by AzureAndy** [sairashaik6677/azuresavingsdashboard#4]
Whilst the ACD savings seem to be calculated correctly, the Reservation and Savings plan don't.  This is for an Enterprise Agreement.
Any ideas? 

![Savings](https://github.com/sairashaik6677/azuresavingsdashboard/assets/135042303/bbbbc203-4de0-4a27-9021-769b29fdc7f9)

Also, using data from the PowerBI Pro Azure Cost Management App, the savings don't match. 
![Databricks_savings](https://github.com/sairashaik6677/azuresavingsdashboard/assets/135042303/74a14c32-95e8-4652-85e3-276fe365914f)

The savings figure in this template for databricks matches the cost with RI figure - the actual savings figure is lower.  The Azure Cost Management App has of course been developed by Microsoft so I _presume_ its working correctly.

Many Thanks for your help.

**Comment by AzureAndy** [comment]
Hi,

I notice you closed this ticket but didn’t answer my query.  Could you take another look?

Thanks

Andrew Weager
Senior License Advisory Consultant
M: +44 790 300 3782
***@***.******@***.***>
<http://www.linkedin.com/>Visit my LinkedIn profile<https://www.linkedin.com/in/andyweager>
<http://www.linkedin.com/>www.livingstone-tech.com<http://www.livingstone-tech.com/>

[cid:microsoftteams-image(2)_82a362a4-8526-4e95-8acf-e18f766da18a.png]
Galaxy House, Unit 3, 32 Leonard Street. London. EC2A 4LZ. United Kingdom
[cid:linkedin_teal(003)_bbbeb508-68b0-41af-9bc1-bd0c26c04569.png]<https://www.linkedin.com/company/livingstonegroup/>

This message may contain confidential information solely for its intended recipients and others may not distribute, copy or use it.
If you have received this communication in error, please tell us either by return e-mail or at the numbers above and delete it, and any copies of.
This email may not be used as a commitment to contract or any form of purchase order unless it is accompanied by an official PDF purchase order.
If you have any questions or concerns please contact Livingstone Technologies Limited +44 (0)118 991 3454

<https://www.livingstone-group.com/news-events/content-resources/2021-gartner-magic-quadrant-leader?refer=gartneremailbanner>

**Comment by sairashaik6677** [comment]
The savings figure in this template for databricks matches the cost with RI figure - the actual savings figure is lower. The Azure Cost Management App has of course been developed by Microsoft so I presume its working correctly.

Please read the instructions to setup the $ symbol needs to be changed to the base currency as per Billing Currency in the File. There are no conversions being made in this dashboard.

If you presume Microsoft Management App is working fine - Please feel free to use it. I created this based on the public documentation provided in the Microsoft articles to calculate savings.
