### ISSUE TITLE
Tag need to be separate - ACD question

### ISSUE THREAD

**Issue by Schmja** [sairashaik6677/azuresavingsdashboard#5]
Hi,
thanks for this really helpful PowerBI. 
Its good to see the possibility to have a look on TAGS, but you only give the possibility to have a combination of TAGS. I would like to be able to open it separated. Please see attached - in this example I would like to sort out all technical contacts for a special technican.
<img width="1017" alt="Tags" src="https://github.com/sairashaik6677/azuresavingsdashboard/assets/141025269/70959e33-2f7a-49e9-a4c0-d03f4192674f">

In addition for me its not really clear how do you calculate the ACD Azure Commitment Discount Savings. I have an Enterprise agreement with Azure Monetary Commit - not really much and do not get any discounts on the price list - so what do you mean with these savings? against the actual price list?

Thanks,
Jana

**Comment by sairashaik6677** [comment]
Tags are JSON filed so can't be seperated.
ACD = PayG Price - Discounted price i.e, if you would have had Azure commitment discount how much you would be paying as per PayG price - Discounted price due to Azure commitment. That will be the saving
Ex: PayG = $100 and discounted is =$90 = Savings $10
