### ISSUE TITLE
Question on double discount

### ISSUE THREAD

**Issue by simonarbel** [sairashaik6677/azuresavingsdashboard#6]
Hi 

Does the dashboard consider the case when the customer is getting is a double discount of ACD + RI or ACD +SP?

or just the case where the RI saving is limited due to relatively high ACD?

Thanks
Simon

**Comment by sairashaik6677** [comment]
ACD + RI or ACD+ SP wont be applied. RI and SP will be higher discount so they will be applied. If no RI and SP, ACD will be applied. Net net whatever is the highest discount only that discounting type is applied on savings.

**Comment by simonarbel** [comment]
Not sure I’m following…

Please see attached screenshot of customer data. He’s getting RI discount on top of ACD discount. Does the figure $5.6M in total savings reflects that?

***@***.***

**Comment by sairashaik6677** [comment]
That can't be the case, Need to deep dive to check the data. Can't comment on this.

**Comment by simonarbel** [comment]
I can show you the data if you want.

I compared RI savings in the ACM tool with your dashboard and for some reason the RI savings amount is equal to the on demand amount in the ACM tool

***@***.***

[A screenshot of a computer  Description automatically generated]
