### ISSUE TITLE
I would like to use this dashboard but we are MCA Customer

### ISSUE THREAD

**Issue by camilohtaborda** [sairashaik6677/azuresavingsdashboard#7]
Hello Saira,

Thanks for this tool, but when I tried to customize for MCA customer file is not the same fields and columns than the EA customers file. Could you give us some instructions to have this dashboard for a MCA customer?

Thanks in advance.

**Comment by sairashaik6677** [comment]
It wont support MCA

**Comment by M-Eslam** [comment]
Hello @camilohtaborda , @sairashaik6677 
We have just changed from EA to MCA as well, is there any similar report you have/found that gives similar dashboards for MCA customers ?

**Comment by sairashaik6677** [comment]
Hi @M-Eslam - This dashboard doesn't support MCA. I am not aware of any similar dashboards for MCA customers.
